// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseFile(arg1:string,arg2:string):Promise<string>;

export function BrowseFolder(arg1:string):Promise<string>;

export function DownloadAgent():Promise<void>;

export function DownloadAndStartAgent():Promise<void>;

export function DownloadLocalization(arg1:number):Promise<string>;

export function EnsureAgent():Promise<void>;

export function FetchGameDetail(arg1:number):Promise<Record<string, any>>;

export function FetchGames(arg1:number,arg2:number,arg3:string):Promise<Record<string, any>>;

export function FetchSubscription(arg1:string):Promise<Record<string, any>>;

export function GetAgentPath():Promise<string>;

export function GetAgentStatus():Promise<Record<string, any>>;

export function GetLogPath():Promise<string>;

export function GetLogs():Promise<Array<string>>;

export function IsAgentInstalled():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function RefreshToken(arg1:string):Promise<main.LoginResult>;

export function ScanGames(arg1:string):Promise<Array<main.DetectedGame>>;

export function StartAgent():Promise<void>;

export function StopAgent():Promise<void>;
