// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseFile(arg1, arg2) {
  return window['go']['main']['App']['BrowseFile'](arg1, arg2);
}

export function BrowseFolder(arg1) {
  return window['go']['main']['App']['BrowseFolder'](arg1);
}

export function DownloadAgent() {
  return window['go']['main']['App']['DownloadAgent']();
}

export function DownloadAndStartAgent() {
  return window['go']['main']['App']['DownloadAndStartAgent']();
}

export function DownloadLocalization(arg1) {
  return window['go']['main']['App']['DownloadLocalization'](arg1);
}

export function FetchGameDetail(arg1) {
  return window['go']['main']['App']['FetchGameDetail'](arg1);
}

export function FetchGames(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchGames'](arg1, arg2, arg3);
}

export function FetchSubscription(arg1) {
  return window['go']['main']['App']['FetchSubscription'](arg1);
}

export function GetAgentPath() {
  return window['go']['main']['App']['GetAgentPath']();
}

export function GetAgentStatus() {
  return window['go']['main']['App']['GetAgentStatus']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function IsAgentInstalled() {
  return window['go']['main']['App']['IsAgentInstalled']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function RefreshToken(arg1) {
  return window['go']['main']['App']['RefreshToken'](arg1);
}

export function ScanGames(arg1) {
  return window['go']['main']['App']['ScanGames'](arg1);
}

export function StartAgent() {
  return window['go']['main']['App']['StartAgent']();
}

export function StopAgent() {
  return window['go']['main']['App']['StopAgent']();
}
