// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1, arg2) {
  return window['go']['main']['App']['AddFavorite'](arg1, arg2);
}

export function BrowseFile(arg1, arg2) {
  return window['go']['main']['App']['BrowseFile'](arg1, arg2);
}

export function BrowseFolder(arg1) {
  return window['go']['main']['App']['BrowseFolder'](arg1);
}

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DownloadLocalization(arg1) {
  return window['go']['main']['App']['DownloadLocalization'](arg1);
}

export function FetchFavorites(arg1) {
  return window['go']['main']['App']['FetchFavorites'](arg1);
}

export function FetchGameDetail(arg1) {
  return window['go']['main']['App']['FetchGameDetail'](arg1);
}

export function FetchGames(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchGames'](arg1, arg2, arg3);
}

export function FetchSubscription(arg1) {
  return window['go']['main']['App']['FetchSubscription'](arg1);
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Install(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Install'](arg1, arg2, arg3, arg4);
}

export function InstallLocal(arg1, arg2) {
  return window['go']['main']['App']['InstallLocal'](arg1, arg2);
}

export function IsBusy() {
  return window['go']['main']['App']['IsBusy']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['App']['OpenReleasePage'](arg1);
}

export function PerformUpdate() {
  return window['go']['main']['App']['PerformUpdate']();
}

export function RefreshToken(arg1) {
  return window['go']['main']['App']['RefreshToken'](arg1);
}

export function RemoveFavorite(arg1, arg2) {
  return window['go']['main']['App']['RemoveFavorite'](arg1, arg2);
}

export function ScanGames(arg1) {
  return window['go']['main']['App']['ScanGames'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['main']['App']['Uninstall'](arg1);
}
