// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFavorite(arg1:string,arg2:number):Promise<Record<string, any>>;

export function BrowseFile(arg1:string,arg2:string):Promise<string>;

export function BrowseFolder(arg1:string):Promise<string>;

export function CancelInstall():Promise<void>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function DownloadLocalization(arg1:number):Promise<string>;

export function FetchFavorites(arg1:string):Promise<Record<string, any>>;

export function FetchGameDetail(arg1:number):Promise<Record<string, any>>;

export function FetchGames(arg1:number,arg2:number,arg3:string):Promise<Record<string, any>>;

export function FetchSubscription(arg1:string):Promise<Record<string, any>>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetLogPath():Promise<string>;

export function GetLogs():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function Install(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function InstallLocal(arg1:string,arg2:string):Promise<void>;

export function IsBusy():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function OpenReleasePage(arg1:string):Promise<void>;

export function PerformUpdate():Promise<void>;

export function RefreshToken(arg1:string):Promise<main.LoginResult>;

export function RemoveFavorite(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ScanGames(arg1:string):Promise<Array<main.DetectedGame>>;

export function Uninstall(arg1:string):Promise<void>;
